name: torch-kindle
channels:
  - conda-forge
  - defaults
  - pytorch
  -
dependencies:
  - python=3.8
  - black=20.8b1
  - mypy=0.800
  - flake8=3.8.4
  - isort=5.7.0
  - pytest=6.2.1
  - pytest-flake8=1.0.7
  - pytest-mypy=0.8.0
  - pytest-pylint=0.18.0
  - coverage=5.3
  - pytest-cov=2.10.1
  - pip:
    - pre-commit==2.9.3
    - pytest-sugar==0.9.4
    - pytest-clarity==0.3.0a0
    - pytest-xdist==2.2.0
    - docformatter==1.3.1
    - pdoc3==0.9.2
